name: boustro
description: >
  A rich text editor for Flutter.

version: 0.2.0
homepage: https://jjagg.dev/boustro
repository: https://github.com/Jjagg/boustro

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  built_collection: ^5.0.0
  characters: ^1.1.0
  collection: ^1.15.0
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  meta: ^1.2.4

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
