codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "10...100"

  status:
    project:
      default:
        # For now let's not mark builds as failed for bad coverage
        # Once coverage is higher we can enable this and put a
        # suitable threshold in place.
        informational: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no

