name: example
description: example
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  boustro_starter:
    path: ../

  flutter:
    sdk: flutter

  image_picker: ^0.7.2
  media_gallery: ^0.1.5
  url_launcher: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
