name: example
description: example
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  boustro_starter:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.0.0

flutter:
  uses-material-design: true
