name: boustro_starter
description: >
  Attributes, line modifiers and embeds to get started with boustro,
  a rich text editor for Flutter.

publish_to: none
version: 0.1.0-0
homepage: https://jjagg.dev/boustro
repository: https://github.com/Jjagg/boustro

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  boustro:
    path: ../boustro
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
