name: boustro_starter
description: >
  Attributes, line modifiers and embeds to get started with boustro,
  a rich text editor for Flutter.

version: 0.1.0
homepage: https://jjagg.dev/boustro
repository: https://github.com/Jjagg/boustro

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  boustro:
    path: ../boustro
  collection: ^1.15.0
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_spanned_controller: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
