name: flutter_spanned_controller
description: >
  TextEditingController implementation that allows for rich text styling in
  Flutter.

version: 0.5.0+2
homepage: https://jjagg.dev/boustro
repository: https://github.com/Jjagg/boustro

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.1.0-10.0.pre'

dependencies:
  built_collection: ^5.0.0
  characters: ^1.1.0
  collection: ^1.15.0
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  meta: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
