name: Build

on:
  push:
  pull_request:

jobs:
  flutter:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        channel:
        - beta
        package:
          - packages/flutter_spanned_controller
          - packages/boustro
          - packages/boustro_starter
          - example

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.channel }}

      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ matrix.package }}

      - name: Check format
        run: flutter format --set-exit-if-changed .
        working-directory: ${{ matrix.package }}

      - name: Analyze
        run: flutter analyze
        working-directory: ${{ matrix.package }}

      - name: Run tests
        run: flutter test -r expanded
        working-directory: ${{ matrix.package }}
