name: Build

on:
  push:
    paths-ignore:
      - "docs/**"
  pull_request:
    paths-ignore:
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        channel:
          - dev
        package:
          - packages/flutter_spanned_controller
          - packages/boustro
          - packages/boustro_starter
          - packages/flutter_spanned_controller/example
          - packages/boustro_starter/example
        include:
          - package: packages/boustro_starter
            no-tests: true
          - package: packages/flutter_spanned_controller/example
            no-tests: true
          - package: packages/boustro_starter/example
            no-tests: true

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.channel }}

      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ matrix.package }}

      - name: Check format
        run: flutter format --set-exit-if-changed .
        working-directory: ${{ matrix.package }}

      - name: Analyze
        run: flutter analyze
        working-directory: ${{ matrix.package }}

      - name: Run tests
        run: flutter test -r expanded --coverage
        working-directory: ${{ matrix.package }}
        if: ${{ !matrix.no-tests }}

      - uses: codecov/codecov-action@v1
        with:
          file: ${{ format('./{0}/coverage/lcov.info', matrix.package) }}
          name: ${{ matrix.package }}
          fail_ci_if_error: true
        if: ${{ !matrix.no-tests }}
